### ISSUE TITLE
Script Fails

### ISSUE THREAD

**Issue by epienaarIDBS** [blackducksoftware/bd_export_spdx2.2#23]
Hi,
I get this error when trying to run it:
Traceback (most recent call last):
  File "bd_export_spdx2.2/bd_export_spdx2.2.py", line 42, in <module>
    main.run()
  File "bd_export_spdx2.2/export_spdx/main.py", line 141, in run
    process.process_project(project, version, toppackage, hierarchical_bom, bearer_token, exclude_ignored_components)
  File "bd_export_spdx2.2/export_spdx/process.py", line 342, in process_project
    compcount += process_project(subproj, subver,
  File "bd_export_spdx2.2/export_spdx/process.py", line 241, in process_project
    comp_data_dict = asyncio.run(async_main(bom_compsdict, bearer_token, version))
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "bd_export_spdx2.2/export_spdx/process.py", line 386, in async_main
    all_copyrights = dict(await asyncio.gather(*copyright_tasks))
  File "bd_export_spdx2.2/export_spdx/process.py", line 428, in async_get_copyrights
    result_data = await resp.json()
  File "/home/user/.local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1119, in json
    return loads(stripped.decode(encoding))
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 14469 (char 14468)
2022-11-08 11:58:45,929:ERROR:Task exception was never retrieved
future: <Task finished name='Task-3009' coro=<async_get_files() done, defined at bd_export_spdx2.2/export_spdx/process.py:473> exception=KeyError('items')>
Traceback (most recent call last):
  File "bd_export_spdx2.2/export_spdx/process.py", line 492, in async_get_files
    cfile = result_data['items']
KeyError: 'items'

It looks like a JSON decoder error?
Please let me know either way
Thanks

**Comment by matthewb66** [comment]
This script has been deprecated as stated in the Readme.

It is OSS provided without warranty or liability, so if you encounter a problem you are welcome to investigate and propose a fix/change as a pull request.

Thanks
